export const GET_RECIPES = 'GET_RECIPES';
export const GET_LATEST_RECIPES = 'GET_LATEST_RECIPES';
export const GET_USER_RECIPES = 'GET_USER_RECIPES';
export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const RECIPE_ERROR = 'RECIPE_ERROR';
export const SET_CURRENT_RECIPE = 'SET_CURRENT_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const RECIPE_LOADING = 'RECIPE_LOADING';

export const AUTH_LOADING = 'AUTH_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_CLEAR_ERRORS = 'USER_CLEAR_ERRORS';
export const USER_SET_ERRORS = 'USER_SET_ERRORS';

export const GET_USER = 'GET_USER';
