export const GET_RECIPES = 'GET_RECIPES';
export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const RECIPE_ERROR = 'RECIPE_ERROR';
export const SET_CURRENT_RECIPE = 'SET_CURRENT_RECIPE';
export const CLEAR_CURRENT_RECIPE = 'CLEAR_CURRENT_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
